// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh82hlA46rwjM8BF1MzkOQJGUDDe9OR00',
    appId: '1:554042331677:web:71211c8986299cad472cf4',
    messagingSenderId: '554042331677',
    projectId: 'projetfinal-firebase',
    authDomain: 'projetfinal-firebase.firebaseapp.com',
    storageBucket: 'projetfinal-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC13sBt5Lr6PTJo9fvQ_OWO6dpEVeNSfsU',
    appId: '1:554042331677:android:b1cc6e70b4738cd9472cf4',
    messagingSenderId: '554042331677',
    projectId: 'projetfinal-firebase',
    storageBucket: 'projetfinal-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4LbJIoK9h1G1vP9oUSrsTlzlkefrIO6I',
    appId: '1:554042331677:ios:b5a115696ee220a2472cf4',
    messagingSenderId: '554042331677',
    projectId: 'projetfinal-firebase',
    storageBucket: 'projetfinal-firebase.appspot.com',
    iosBundleId: 'com.example.tpfFirebase',
  );
}
